version: "3"
services:
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - C:/docker_test/app:/var/www/html/
    links:
      - db
    networks:
      - default
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal start_with_request=yes remote_enable=1 remote_port=10000 client_port=10000"
      PHP_IDE_CONFIG: "serverName=Docker"
  db:
    image: mysql:8.0.16
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - C:/docker_test/dump:/docker-entrypoint-initdb.d
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - db:db
    ports:
      - 8010:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password